<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerS0Cgh8Y\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerS0Cgh8Y/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerS0Cgh8Y.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerS0Cgh8Y\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerS0Cgh8Y\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'S0Cgh8Y',
    'container.build_id' => '4f850a90',
    'container.build_time' => 1611357330,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerS0Cgh8Y');
