<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQJigs4S\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQJigs4S/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQJigs4S.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQJigs4S\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQJigs4S\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QJigs4S',
    'container.build_id' => '0e1a69d3',
    'container.build_time' => 1612741980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQJigs4S');
